//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoYP0101
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrears
    {
        public int Id { get; set; }
        public int AdressId { get; set; }
        public string Flat { get; set; }
        public int UserId { get; set; }
        public string Phone { get; set; }
        public decimal Water { get; set; }
        public Nullable<decimal> ElectricPower { get; set; }
    
        public virtual ListHousingStock ListHousingStock { get; set; }
    }
}
