//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoYP0101
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListHousingStock
    {
        public ListHousingStock()
        {
            this.Arrears = new HashSet<Arrears>();
            this.PaymentReport = new HashSet<PaymentReport>();
        }
    
        public int Id { get; set; }
        public string Adress { get; set; }
        public System.DateTime Beginning { get; set; }
        public string Floors { get; set; }
        public string Flat { get; set; }
        public string Year { get; set; }
        public decimal Square { get; set; }
    
        public virtual ICollection<Arrears> Arrears { get; set; }
        public virtual ICollection<PaymentReport> PaymentReport { get; set; }
    }
}
