//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoYP0101
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReport
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AdressId { get; set; }
        public string Flat { get; set; }
        public string Period { get; set; }
        public decimal Accrued { get; set; }
        public Nullable<decimal> Paid { get; set; }
    
        public virtual ListHousingStock ListHousingStock { get; set; }
        public virtual Users Users { get; set; }
    }
}
